# Generated by Django 6.0.3 on 2026-05-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dnasequence',
            options={'ordering': ['-created_at']},
        ),
    ]
