# Generated by Django 6.0.3 on 2026-05-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auditlog_emailverificationtoken_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='fullname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='protein',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, upload_to='proteins/pdb/'),
        ),
    ]
