# Generated by Django 6.0.3 on 2026-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='agent_messages_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
